# Generated by Django 3.2.7 on 2021-10-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
